### ISSUE TITLE
Results Uploaded to Azure Test Runs

### ISSUE THREAD

**Issue by Denzil8** [jeffpriz/vsts-release-web-test#11]
Option to publish the outcome as a test result since this can be used in the pipeline logic or reporting.

**Comment by jeffpriz** [comment]
I will investigate this as an addition to the functionality

**Comment by Denzil8** [comment]
From the research i have done it is possible to upload the result if it is in a specific xml format (for nunit test results), below is a link i have found describing such format. If the output of the task can create such xml file one can than use the Microsoft test task to select such file as a result to be uploaded.

https://github.com/nunit/docs/wiki/Test-Result-XML-Format
