### ISSUE TITLE
Parameterized URLs

### ISSUE THREAD

**Issue by wds1777** [jeffpriz/vsts-release-web-test#12]
Can I do this:

https://{version}/myApp.com

so that I can supply different urls depending on a environment variable?

**Comment by bothzoli** [comment]
you can do it if you have `version` defined as a pipeline variable, like such:
`https://$(version)/myApp.com`

**Comment by jeffpriz** [comment]
Yes, as indicated above, the variable format in Azure DevOps is $(variableNameHere)

so I regularly do things like:

https://$(devEnvironmentServer)/MyApp/HealthCheck
