### ISSUE TITLE
RollBack Strategy for Smoke test failure

### ISSUE THREAD

**Issue by kmahesh25** [jeffpriz/vsts-release-web-test#16]
Is there any way to deploy last successful release when the smoke test is failed

**Comment by jeffpriz** [comment]
Certainly possible.  You could develop a Rollback stage to your pipeline that would only execute if the deployment stage failed.  Placing the Smoke Test at the end of your deployment stage would be a great way to validate things are at least "up" after the deployment steps have completed.. then a failure of the smoke test would fail your deployment stage and then trigger your rollback stage.

**Comment by kmahesh25** [comment]
Perfect
