### ISSUE TITLE
Remove max retries limit

### ISSUE THREAD

**Issue by nicolasg-playster** [jeffpriz/vsts-release-web-test#3]
Why is there an arbitrary max retries limit of 12?

We have some systems that can take 1-5 mins to initialize. The 12 retries limit is way too low to account for this. Can we remove this limit or at least put a maximum that is more sensible (e.g. 100) so that we don't need to put long delays as a workaround?

Thanks

**Comment by jeffpriz** [comment]
The max retries is there more as a safeguard, it is there to limit people from abusing the task as a way to spam a url... utilizing the task in a less-than-intended way.    The ability to set a delay time between tries lets you get through long-running initialization.  12 retries with a 30 second delay between attempts gets you 6 minutes of attempts.  That feels "good" to me.  What are your troubles with that usage? I am open to increasing the max retry limit by a bit, but don't know that moving it up to something like 100 feels appropriate. 

Let me know the troubles you're having with having a long delay amount and I can figure out what I think makes the best solution.

thanks

Jeff

**Comment by jeffpriz** [comment]
I think i *did* have the max retry at something like 20 or 25 originally, I guess I could move it back to that if that helps?
